name: Build

on:
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set release mode
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "::set-env name=REF::$(echo $GITHUB_REF | sed "s:.*/::g")"
 
    - name: Set edge mode
      if: "!startsWith(github.ref, 'refs/tags/')"
      run: |
        echo "::set-env name=REF::edge"
        echo "::set-env name=TIMESTAMP::$(date -u +%Y%m%d-%H%Mz)"
 
    - name: Build
      run: make

    - name: Publish pem-files
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: target/certpub-*.pem
        type: application/x-pem-file

    - name: Publish p12-files
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: target/certpub-*.p12
        type: application/x-pkcs12

    - name: Publish jks-files
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: target/certpub-*.jks
        type: application/x-java-keystore

    - name: Publish readme file
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: target/README.md
        type: text/markdown

    - name: Publish checksum files
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: target/*sums.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      if: "!startsWith(github.ref, 'refs/tags/')"
      with:
        name: certpub-issuers-edge-${{ env.TIMESTAMP }}
        path: target/*