name: Build

on:
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set release mode
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "::set-env name=REF::$(echo $GITHUB_REF | sed "s:.*/::g")"
 
    - name: Set edge mode
      if: "!startsWith(github.ref, 'refs/tags/')"
      run: echo "::set-env name=REF::edge"
 
    - name: Build
      run: make

    - name: Publish pem-files
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          for env in $(ls src); do
            upload \
              -f target/certpub-$env-${TAG}.pem \
              -n "certpub-$env-${TAG}.pem" \
              -t "application/x-pem-file"
          done

    - name: Publish p12-files
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          for env in $(ls src); do
            upload \
              -f target/certpub-$env-${TAG}.p12 \
              -n "certpub-$env-${TAG}.p12" \
              -t "application/x-pkcs12"
          done

    - name: Publish checksums
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/checksums.txt